name: 'site'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true

jobs:

  site:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - uses: actions/checkout@v3

    - run: python -m pip install recommonmark sphinx sphinx_rtd_theme

    - run: |
        mv README.md README.ign
        make html
        mv README.ign README.md

    - name: 'publish site to gh-pages'
      if: github.event_name != 'pull_request' && github.repository == 'buildthedocs/buildthedocs.github.io'
      run: |
        cd _build/html
        git init
        cp ../../.git/config ./.git/config
        cp ../../README.md ./
        touch .nojekyll
        git add .
        git config --local user.email "BuildTheDocs@GitHubActions"
        git config --local user.name "GitHub Actions"
        git commit -a -m "update ${{ github.sha }}"
        git push -u origin +HEAD:main
