name: 'site'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true

jobs:

  site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v1
    - run: python -m pip install recommonmark sphinx sphinx_rtd_theme
    - run: |
        mv README.md README.ign
        make html
        mv README.ign README.md
    - name: 'publish site to gh-pages'
      if: github.event_name != 'pull_request' && github.repository == 'buildthedocs/buildthedocs.github.io'
      env:
        GH_DEPKEY: ${{ secrets.GHA_DEPLOY_KEY }}
      run: |
        cd _build/html
        cp ../../README.md ./
        touch .nojekyll
        git init
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -a -m "update ${{ github.sha }}"
        git remote add origin "git@github.com:${{ github.repository }}"
        eval `ssh-agent -t 60 -s`
        echo "$GH_DEPKEY" | ssh-add -
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git push -u origin +HEAD:master
        ssh-agent -k
